-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID # 자식 아이템 정보
JOIN ITEM_INFO C ON B.PARENT_ITEM_ID = C.ITEM_ID # 부모 아이템 정보
WHERE C.RARITY = 'RARE'
ORDER BY A.ITEM_ID DESC
