-- 코드를 작성해주세요

SELECT SUM(G.SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE G
JOIN HR_EMPLOYEES E ON G.EMP_NO = E.EMP_NO
JOIN HR_DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID
GROUP BY E.EMP_NO
ORDER BY SCORE DESC
LIMIT 1